# Type of the devices required
string type

---

# List of components as yaml string
temoto_component_manager/Component[] local_components

# List of components as yaml string
temoto_component_manager/Component[] remote_components
